send_call:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: ha_ivr
    message:
      required: true
      example: "The front door was opened"
      selector:
        text:
          multiline: true
    phones:
      required: true
      example: "0501234567,0521234567"
      selector:
        text:
    trunk:
      required: false
      example: "sip_trunk_2"
      selector:
        text:
    caller_id:
      required: false
      example: "0501234567"
      selector:
        text:
    retries:
      required: false
      example: 2
      selector:
        number:
          min: 0
          max: 5
          mode: box
